adapter: "FF:FF:FF:FF:FF:FF" # Optional
devices:
- name: My Device
  mac_address: "00:00:00:00:00:00"
  password: '0000'
  default_color: "disco"    # Optional, defaults to white
  actions: # Optional, invoked in addition to database
    on_facet_change: ""
    on_connect: ""
    on_disconnect: ""
  facets:
  - value: "studying"       #1
    color: "red"
  - value: "chores"         #2
    color: "blue"
  - value: "writing"        #3
  - value: "development"    #4
  - value: "reading"        #5
  - value: "streaming"      #6
  - value: "exercise"       #7
  - value: "administrivia"  #8
  - value: "television"     #9
  - value: "break"          #10
  - value: "music"          #11
  - value: "meeting"        #12
