version: '3.4'

services:
# May also need 'Privileged' here
  time-tracker:
    build:
      context: .
    container_name: 'timeflip-tracker'
    volumes:
    - /var/run/dbus/:/var/run/dbus/
    - ./config/config.yaml:/etc/timeflip-tracker/config.yaml
    environment:
    - MARIADB_HOST=0.0.0.0
    - MARIADB_PORT=3307
    - MARIADB_DATABASE=timeflip
    - MARIADB_USER=timeflip
    - MARIADB_PASSWORD=password
  database:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MARIADB_DATABASE=timeflip
      - MARIADB_USER=timeflip
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=1
